services:
  db:
    image: postgres:16
    container_name: villamill-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: villamill
    ports:
      - "5433:5432"
    volumes:
      - villamill_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: villamill-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  villamill_pgdata:
